https://localhost:5053

### 
GET http://localhost:5053/notes


###
POST http://localhost:5053/notes
Content-Type: application/json

{
  "title": "First Note",
  "content": "This is my first saved note."
}

###
GET http://localhost:5053/notes/6876f2733900911b12778931


### 
PUT http://localhost:5053/notes/6876f2733900911b12778931
Content-Type: application/json

{
  "title": "Updated Note",
  "content": "The content has been one more time.",
  "status": 1
}

###
DELETE http://localhost:5053/notes/{id}

