name: .NET Minimal API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore



    - name: Publish app
      run: dotnet publish -c Release -o ./publish

    - name: Upload published build
      uses: actions/upload-artifact@v4
      with:
        name: NotesAppBackend
        path: ./publish
